name: stellar_arcana
description: "Carta natal horóscopo."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  cupertino_icons: ^1.0.8
  google_fonts: ^5.1.0
  country_state_city_picker: ^1.2.8
  path_provider: ^2.0.0

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
     - assets/welcome.webp
     - assets/fondos/bg1.webp
     - assets/fondos/bg2.webp
     - assets/fondos/bg3.webp
     - assets/fondos/bg4.webp
     - assets/fondos/bg5.webp
     - assets/countries_index.json
     - assets/countries/
     - assets/
     - assets/avatar/aquariusF.webp
     - assets/avatar/aquariusM.webp
     - assets/avatar/ariesF.webp
     - assets/avatar/ariesM.webp
     - assets/avatar/cancerF.webp
     - assets/avatar/cancerM.webp
     - assets/avatar/capricornF.webp
     - assets/avatar/capricornM.webp
     - assets/avatar/geminisF.webp
     - assets/avatar/geminisM.webp
     - assets/avatar/leoF.webp
     - assets/avatar/leoM.webp
     - assets/avatar/libraF.webp
     - assets/avatar/libraM.webp
     - assets/avatar/piscisF.webp
     - assets/avatar/piscisM.webp
     - assets/avatar/sagitarioM.webp
     - assets/avatar/sagitarioF.webp
     - assets/avatar/scorpioF.webp
     - assets/avatar/scorpioM.webp
     - assets/avatar/taurusF.webp
     - assets/avatar/taurusM.webp
     - assets/avatar/virgoF.webp
     - assets/avatar/virgoM.webp




