name: stellar_arcana
description: "Carta natal horóscopo."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  cupertino_icons: ^1.0.8
  google_fonts: ^5.1.0
  country_state_city_picker: ^1.2.8
  path_provider: ^2.0.0

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
     - assets/welcome.webp
     - assets/splash1.webp
     - assets/splash2.webp
     - assets/splash3.webp
     - assets/splash4.webp
     - assets/splash5.webp
     - assets/countries_index.json
     - assets/countries/
     - assets/


